In [2]:
import numpy as np

In [3]:
a = np.array([[1, 3, 5], [2, 4, 6], [9, 8, 7]])
print "The A matrix:\n", a

The A matrix:
[[1 3 5]
 [2 4 6]
 [9 8 7]]


In [7]:
a = np.eye(5)
print "The Identity matrix:\n", a

The Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
a = np.ones((5, 7))
print "The matrix of ones:\n", a

The matrix of ones:
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [4]:
a = np.zeros((3, 5))
print "The matrix of zeros:\n", a

The matrix of zeros:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
v = np.arange(0, 24, 2)
print "The row vector:\n", v

The row vector:
[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [12]:
d = v.reshape(3, 4)
print "The matrix from the reshaped row vector 'v':\n", d

The matrix from the reshaped row vector 'v':
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [15]:
print "The third element of the second row of matrix 'd':", d[1, 2]

The third element of the second row of matrix 'd': 12


In [17]:
print "The third row of matrix 'd':", d[2, :]

The third row of matrix 'd': [16 18 20 22]


In [18]:
print "The fourth column of matrix 'd':", d[:, 3]

The fourth column of matrix 'd': [ 6 14 22]


In [20]:
print "The elements (1, 2) and (3, 3):", d[[0, 2], [1, 2]]

The elements (1, 2) and (3, 3): [ 2 20]


In [25]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print "The a vector:\n", a
print "Its' shape:", a.shape
print "Two-dimensional array:\n", b
print "Its' shape:", b.shape

 The a vector:
[1 2 3]
Its' shape: (3L,)
Two-dimensional array:
[[1]
 [2]
 [3]]
Its' shape: (3L, 1L)


In [31]:
print "Transposition doesn't change a vector a!", a.T

Transposition doesn't change a vector a! [1 2 3]


In [30]:
print "But changes the array b...", b.T

But changes the array b... [[1 2 3]]


In [37]:
a = np.array([[1, 2, 3], [2, 4, 5]])
b = np.array([[0, 1], [5, 0], [4, 0]])
c = np.dot(a, b)
print "The a matrix:\n", a
print "The b matrix:\n", b
print "The result of multiplication of a and b:\n", c

The a matrix:
[[1 2 3]
 [2 4 5]]
The b matrix:
[[0 1]
 [5 0]
 [4 0]]
The result of multiplication of a and b:
[[22  1]
 [40  2]]


In [38]:
v = np.array([1 ,2])
d = np.dot(c, v)
print d

[24 44]


In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T
print a
print "Transposition with a function:\n", b
print "Transposition with a method:\n", c

[[1 2]
 [3 4]]
Transposition with a function:
[[1 3]
 [2 4]]
Transposition with a method:
[[1 3]
 [2 4]]


In [52]:
a = np.array([[1, 3, 5], [4, 9, 0], [2, 4, 3]], dtype=float)
det = np.linalg.det(a)

In [46]:
print "The determinant of matrix\n", a
print "equals:", det

The determinant of matrix
[[1. 3. 5.]
 [4. 9. 0.]
 [2. 4. 3.]]
equals: -18.999999999999996


In [54]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)

In [55]:
print "The a matrix rank\n", a
print "equals:", r

The a matrix rank
[[1 2 3]
 [1 1 1]
 [2 2 2]]
equals: 2


In [56]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)

In [57]:
print "Matrix a:\n", a
print "Vector b:\n", b
print "The system solution:\n", x

Matrix a:
[[3 1]
 [1 2]]
Vector b:
[9 8]
The system solution:
[2. 3.]


In [58]:
print "Check:", np.dot(a, x)

Check: [9. 8.]


In [71]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=float)
b = np.linalg.inv(a)
c = np.dot(a, b)

In [73]:
print "Matrix a:\n", a
print "Inverse matrix:\n", b
print "The multiplication of a matrix and its inverse matrix must give the identity matrix:\n", c

Matrix a:
[[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Inverse matrix:
[[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
The multiplication of a matrix and its inverse matrix must give the identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [74]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [75]:
print "The matrix a:\n", a
print "Eigen values:\n", w
print "Eigen vectors:\n", v

The matrix a:
[[-1 -6]
 [ 2  6]]
Eigen values:
[2. 3.]
Eigen vectors:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]
